const VERBS = [
  { v:"hablar", ja:"話す",
    presente:["hablo","hablas","habla","hablamos","hablan"],
    indefinido:["hablé","hablaste","habló","hablamos","hablaron"],
    imperfecto:["hablaba","hablabas","hablaba","hablábamos","hablaban"],
    futuro:["hablaré","hablarás","hablará","hablaremos","hablarán"],
    condicional:["hablaría","hablarías","hablaría","hablaríamos","hablarían"],
    subjuntivo:["hable","hables","hable","hablemos","hablen"],
    perfecto:["he hablado","has hablado","ha hablado","hemos hablado","han hablado"],
    imperativo:["habla","hable","hablemos","hablen"] },
  { v:"comer", ja:"食べる",
    presente:["como","comes","come","comemos","comen"],
    indefinido:["comí","comiste","comió","comimos","comieron"],
    imperfecto:["comía","comías","comía","comíamos","comían"],
    futuro:["comeré","comerás","comerá","comeremos","comerán"],
    condicional:["comería","comerías","comería","comeríamos","comerían"],
    subjuntivo:["coma","comas","coma","comamos","coman"],
    perfecto:["he comido","has comido","ha comido","hemos comido","han comido"],
    imperativo:["come","coma","comamos","coman"] },
  { v:"vivir", ja:"住む/生きる",
    presente:["vivo","vives","vive","vivimos","viven"],
    indefinido:["viví","viviste","vivió","vivimos","vivieron"],
    imperfecto:["vivía","vivías","vivía","vivíamos","vivían"],
    futuro:["viviré","vivirás","vivirá","viviremos","vivirán"],
    condicional:["viviría","vivirías","viviría","viviríamos","vivirían"],
    subjuntivo:["viva","vivas","viva","vivamos","vivan"],
    perfecto:["he vivido","has vivido","ha vivido","hemos vivido","han vivido"],
    imperativo:["vive","viva","vivamos","vivan"] },
  { v:"ser", ja:"〜である",
    presente:["soy","eres","es","somos","son"],
    indefinido:["fui","fuiste","fue","fuimos","fueron"],
    imperfecto:["era","eras","era","éramos","eran"],
    futuro:["seré","serás","será","seremos","serán"],
    condicional:["sería","serías","sería","seríamos","serían"],
    subjuntivo:["sea","seas","sea","seamos","sean"],
    perfecto:["he sido","has sido","ha sido","hemos sido","han sido"],
    imperativo:["sé","sea","seamos","sean"] },
  { v:"estar", ja:"〜にいる",
    presente:["estoy","estás","está","estamos","están"],
    indefinido:["estuve","estuviste","estuvo","estuvimos","estuvieron"],
    imperfecto:["estaba","estabas","estaba","estábamos","estaban"],
    futuro:["estaré","estarás","estará","estaremos","estarán"],
    condicional:["estaría","estarías","estaría","estaríamos","estarían"],
    subjuntivo:["esté","estés","esté","estemos","estén"],
    perfecto:["he estado","has estado","ha estado","hemos estado","han estado"],
    imperativo:["está","esté","estemos","estén"] },
  { v:"tener", ja:"持つ",
    presente:["tengo","tienes","tiene","tenemos","tienen"],
    indefinido:["tuve","tuviste","tuvo","tuvimos","tuvieron"],
    imperfecto:["tenía","tenías","tenía","teníamos","tenían"],
    futuro:["tendré","tendrás","tendrá","tendremos","tendrán"],
    condicional:["tendría","tendrías","tendría","tendríamos","tendrían"],
    subjuntivo:["tenga","tengas","tenga","tengamos","tengan"],
    perfecto:["he tenido","has tenido","ha tenido","hemos tenido","han tenido"],
    imperativo:["ten","tenga","tengamos","tengan"] },
  { v:"ir", ja:"行く",
    presente:["voy","vas","va","vamos","van"],
    indefinido:["fui","fuiste","fue","fuimos","fueron"],
    imperfecto:["iba","ibas","iba","íbamos","iban"],
    futuro:["iré","irás","irá","iremos","irán"],
    condicional:["iría","irías","iría","iríamos","irían"],
    subjuntivo:["vaya","vayas","vaya","vayamos","vayan"],
    perfecto:["he ido","has ido","ha ido","hemos ido","han ido"],
    imperativo:["ve","vaya","vamos","vayan"] },
  { v:"hacer", ja:"する/作る",
    presente:["hago","haces","hace","hacemos","hacen"],
    indefinido:["hice","hiciste","hizo","hicimos","hicieron"],
    imperfecto:["hacía","hacías","hacía","hacíamos","hacían"],
    futuro:["haré","harás","hará","haremos","harán"],
    condicional:["haría","harías","haría","haríamos","harían"],
    subjuntivo:["haga","hagas","haga","hagamos","hagan"],
    perfecto:["he hecho","has hecho","ha hecho","hemos hecho","han hecho"],
    imperativo:["haz","haga","hagamos","hagan"] },
  { v:"poder", ja:"〜できる",
    presente:["puedo","puedes","puede","podemos","pueden"],
    indefinido:["pude","pudiste","pudo","pudimos","pudieron"],
    imperfecto:["podía","podías","podía","podíamos","podían"],
    futuro:["podré","podrás","podrá","podremos","podrán"],
    condicional:["podría","podrías","podría","podríamos","podrían"],
    subjuntivo:["pueda","puedas","pueda","podamos","puedan"],
    perfecto:["he podido","has podido","ha podido","hemos podido","han podido"],
    imperativo:["puede","pueda","podamos","puedan"] },
  { v:"querer", ja:"欲しい/したい",
    presente:["quiero","quieres","quiere","queremos","quieren"],
    indefinido:["quise","quisiste","quiso","quisimos","quisieron"],
    imperfecto:["quería","querías","quería","queríamos","querían"],
    futuro:["querré","querrás","querrá","querremos","querrán"],
    condicional:["querría","querrías","querría","querríamos","querrían"],
    subjuntivo:["quiera","quieras","quiera","queramos","quieran"],
    perfecto:["he querido","has querido","ha querido","hemos querido","han querido"],
    imperativo:["quiere","quiera","queramos","quieran"] },
];

const EXAMPLES = [
  { before:"Ayer yo ", verb:"hablar", tense:"indefinido", p:0, after:" con mi madre.", ja:"昨日、私は母と話した。" },
  { before:"Cuando era niño, yo ", verb:"ir", tense:"imperfecto", p:0, after:" a la escuela caminando.", ja:"子供の頃、私は歩いて学校に通っていた。" },
  { before:"Mañana nosotros ", verb:"comer", tense:"futuro", p:3, after:" en un restaurante nuevo.", ja:"明日、私たちは新しいレストランで食べるだろう。" },
  { before:"En tu lugar, yo ", verb:"hacer", tense:"condicional", p:0, after:" lo mismo.", ja:"あなたの立場なら、私も同じことをするだろう。" },
  { before:"¿", verb:"poder", tense:"condicional", p:1, after:" usted ayudarme?", ja:"手伝っていただけますか？（丁寧な依頼）" },
  { before:"Espero que tú ", verb:"tener", tense:"subjuntivo", p:1, after:" un buen viaje.", ja:"良い旅行になりますように。" },
  { before:"Quiero que ellos ", verb:"ser", tense:"subjuntivo", p:4, after:" felices.", ja:"彼らが幸せであってほしい。" },
  { before:"Yo nunca ", verb:"ir", tense:"perfecto", p:0, after:" a México.", ja:"私はメキシコに行ったことがない。" },
  { before:"¿Alguna vez tú ", verb:"comer", tense:"perfecto", p:1, after:" tacos de verdad?", ja:"本場のタコスを食べたことはありますか？" },
  { before:"¡", verb:"hablar", tense:"imperativo", p:0, after:" más despacio, por favor!", ja:"もっとゆっくり話してください！" },
  { before:"El año pasado, nosotros ", verb:"vivir", tense:"indefinido", p:3, after:" en España.", ja:"去年、私たちはスペインに住んだ。" },
  { before:"Normalmente, yo ", verb:"tener", tense:"presente", p:0, after:" mucho trabajo los lunes.", ja:"普段、月曜日は仕事がたくさんある。" },
  { before:"El próximo año, ellos ", verb:"estar", tense:"futuro", p:4, after:" en Japón.", ja:"来年、彼らは日本にいるだろう。" },
  { before:"Cuando éramos jóvenes, ", verb:"querer", tense:"imperfecto", p:3, after:" viajar mucho.", ja:"若い頃、私たちはたくさん旅行したいと思っていた。" },
  { before:"Este regalo es ", answer:"para", after:" ti.", ja:"このプレゼントは君のためのものだ。", label:"por / para", note:"para+人は「〜のために」という受益者・目的を表す。" },
  { before:"Caminamos ", answer:"por", after:" el parque de camino a casa.", ja:"私たちは家に帰る途中、公園を通って歩いた。", label:"por / para", note:"por は「〜を通って」という経路を表す。「〜に向かって」ならparaになるところだが、ここでは家までの経路上を通っている。" },
  { before:"Trabajo ", answer:"para", after:" ganar dinero.", ja:"お金を稼ぐために働く。", label:"por / para", note:"para+動詞の原形は「〜するために」という目的を表す。" },
  { before:"Gracias ", answer:"por", after:" tu ayuda.", ja:"助けてくれてありがとう。", label:"por / para", note:"por は理由・原因（〜のおかげで、〜に対して）を表す。" },
  { before:"Necesito el informe ", answer:"para", after:" el lunes.", ja:"月曜日までにその報告書が必要だ。", label:"por / para", note:"para+期限は「〜までに」という締め切りを表す。" },
  { before:"Pasamos ", answer:"por", after:" tu casa camino al trabajo.", ja:"仕事に行く途中、君の家のそばを通った。", label:"por / para", note:"por は「〜のそばを」という通過点を表す。目的地ではなく途中で通過した場所を表している。" },
  { before:"Voy ", answer:"a", after:" la escuela todos los días.", ja:"毎日学校に行く。", label:"en / a", note:"行き先を表すときは a を使う（ir a + 場所）。" },
  { before:"Vivo ", answer:"en", after:" México.", ja:"メキシコに住んでいる。", label:"en / a", note:"「〜の中に」という所在を表すときは en を使う。" },
  { before:"¿Tienes el libro? Sí, ", answer:"lo", after:" tengo.", ja:"本を持ってる？うん、持ってるよ。", label:"目的代名詞", note:"男性単数の直接目的語（el libro）は lo に置き換える。" },
  { before:"¿Compraste las manzanas? Sí, ", answer:"las", after:" compré.", ja:"りんごを買った？うん、買ったよ。", label:"目的代名詞", note:"女性複数の直接目的語（las manzanas）は las に置き換える。" },
  { before:"", answer:"Le", after:" voy a dar un regalo a mi madre.", ja:"母にプレゼントをあげるつもりだ。", label:"目的代名詞", note:"間接目的語（〜に）は単数なら le、複数なら les で表す。" },
  { before:"", answer:"Les", after:" escribí una carta a mis amigos.", ja:"友人たちに手紙を書いた。", label:"目的代名詞", note:"間接目的語が複数のときは les を使う。" },
  { before:"¿Ves a Juan? Sí, ", answer:"lo", after:" veo.", ja:"フアンが見える？うん、見えるよ。", label:"目的代名詞", note:"男性の人を指す直接目的語も lo に置き換えられる。" },
  { before:"Yo ", answer:"me levanto", after:" a las siete de la mañana.", ja:"私は朝7時に起きる。", label:"levantarse（再帰動詞・現在形）", note:"再帰動詞は主語に合わせた再帰代名詞（me/te/se/nos/se）を動詞の前につける。" },
  { before:"Ella ", answer:"se llama", after:" María.", ja:"彼女はマリアという名前だ。", label:"llamarse（再帰動詞・現在形）", note:"llamarse は「〜という名前である」。三人称単数は se llama。" },
  { before:"Nosotros ", answer:"nos despertamos", after:" temprano los lunes.", ja:"私たちは月曜日早く目を覚ます。", label:"despertarse（再帰動詞・現在形）", note:"nosotros では再帰代名詞 nos を使う。" },
  { before:"¿A qué hora ", answer:"te acuestas", after:" tú?", ja:"何時に寝るの？", label:"acostarse（再帰動詞・現在形）", note:"tú では再帰代名詞 te を使う。" },
  { before:"Ellos ", answer:"se duchan", after:" por la mañana.", ja:"彼らは朝シャワーを浴びる。", label:"ducharse（再帰動詞・現在形）", note:"三人称複数では再帰代名詞 se を使う。" },
  { before:"Este coche es más caro ", answer:"que", after:" aquel.", ja:"この車はあの車より高い。", label:"比較級", note:"比較級は más+形容詞+que で「〜より…」を表す。" },
  { before:"Ella es ", answer:"tan", after:" alta como su hermana.", ja:"彼女は姉と同じくらい背が高い。", label:"同等比較", note:"同等比較は tan+形容詞+como で「〜と同じくらい」を表す。" },
  { before:"Tengo menos tiempo ", answer:"que", after:" tú.", ja:"私は君より時間が少ない。", label:"比較級", note:"menos+名詞+que で「〜より少ない」を表す。" },
  { before:"Mi hermano es el ", answer:"más", after:" alto de la familia.", ja:"私の兄は家族の中で一番背が高い。", label:"最上級", note:"最上級は el/la+más+形容詞で「一番〜」を表す。" },
  { before:"María ", answer:"es", after:" muy inteligente.", ja:"マリアはとても賢い。", label:"ser / estar", note:"性格・本質的な性質を表すときは ser を使う。" },
  { before:"Hoy yo ", answer:"estoy", after:" un poco cansado.", ja:"今日、私は少し疲れている。", label:"ser / estar", note:"一時的な状態を表すときは estar を使う。" },
  { before:"Madrid ", answer:"está", after:" en España.", ja:"マドリードはスペインにある。", label:"ser / estar", note:"場所・所在を表すときは estar を使う。" },
  { before:"¿Qué hora ", answer:"es", after:"?", ja:"何時ですか。", label:"ser / estar", note:"時刻を表すときは ser を使う。" },
  { before:"La sopa ", answer:"está", after:" fría, caliéntala un poco.", ja:"スープが冷めているから、少し温めて。", label:"ser / estar", note:"一時的な状態（今冷めている）を表すときは estar を使う。「caliéntala（温めて）」から一時的な温度の話だと分かる。" },
  { before:"Él ", answer:"es", after:" médico.", ja:"彼は医者だ。", label:"ser / estar", note:"職業を表すときは ser を使う。" },
  { before:"A mí ", answer:"me gusta", after:" el chocolate.", ja:"私はチョコレートが好きだ。", label:"gustar（現在形）", topic:"gustar", note:"gustarは「主語＝好きな対象」。人は間接目的語代名詞（me/te/le/nos/les）で表す。" },
  { before:"A ella ", answer:"le duele", after:" la cabeza.", ja:"彼女は頭が痛い。", label:"doler（現在形）", topic:"gustar", note:"doler（痛い）もgustarと同じ語順パターンを取る。" },
  { before:"A nosotros ", answer:"nos interesa", after:" la historia.", ja:"私たちは歴史に興味がある。", label:"interesar（現在形）", topic:"gustar", note:"interesar（興味がある）もgustar型。主語は「歴史」なので単数形。" },
  { before:"A ellos ", answer:"les gustan", after:" los tacos.", ja:"彼らはタコスが好きだ。", label:"gustar（現在形）", topic:"gustar", note:"主語（los tacos）が複数なので、動詞も複数形gustanになる。" },
  { before:"A ti ", answer:"te molesta", after:" el ruido.", ja:"あなたは騒音が迷惑だ。", label:"molestar（現在形）", topic:"gustar", note:"molestar（迷惑だ）もgustar型の語順を取る。" },
  { before:"¿Le diste el regalo a Juan? Sí, ", answer:"se lo", after:" di.", ja:"フアンにプレゼントをあげた？うん、それを彼にあげたよ。", label:"目的代名詞（二重）", note:"間接目的語leと直接目的語loが並ぶとき、leはseに変わる。" },
  { before:"¿Me prestas tu coche? Sí, ", answer:"te lo", after:" presto.", ja:"車を貸してくれる？うん、それを君に貸すよ。", label:"目的代名詞（二重）", note:"間接目的語（te）＋直接目的語（lo）は「te lo」の順で並べる。" },
  { before:"¿Les enviaste la carta a ellos? Sí, ", answer:"se la", after:" envié.", ja:"彼らに手紙を送った？うん、それを彼らに送ったよ。", label:"目的代名詞（二重）", note:"間接目的語lesと直接目的語laが並ぶとき、lesはseに変わる。" },
  { before:"¿Nos vas a dar la noticia? Sí, ", answer:"nos la", after:" voy a dar.", ja:"私たちにその知らせを教えてくれる？うん、それを教えるよ。", label:"目的代名詞（二重）", note:"seに変わるのはle/lesが直接目的語lo/laと組み合わさるときだけ。nos/te/meはそのままの形で使う（nos+la→nos la）。" },
  { before:"¿Me compras el libro? Sí, ", answer:"te lo", after:" compro.", ja:"その本を買ってくれる？うん、それを君に買うよ。", label:"目的代名詞（二重）", note:"間接目的語（te）＋直接目的語（lo）は必ずこの順番。" },
  { before:"Confío ", answer:"en", after:" ti.", ja:"私は君を信頼している。", label:"前置詞（en/de）", topic:"preposicion", note:"confiar en（〜を信頼する）は決まった組み合わせ。" },
  { before:"El libro trata ", answer:"de", after:" la historia de México.", ja:"その本はメキシコの歴史についてだ。", label:"前置詞（en/de）", topic:"preposicion", note:"tratar de（〜について扱う）は決まった組み合わせ。" },
  { before:"¿Tienes las entradas? Sí, ", answer:"las", after:" tengo.", ja:"チケットを持ってる？うん、持ってるよ。", label:"目的代名詞", topic:"pronombre", note:"女性複数の直接目的語（las entradas）は las に置き換える。" },
  { before:"¿Conoces a María? Sí, ", answer:"la", after:" conozco.", ja:"マリアを知ってる？うん、知ってるよ。", label:"目的代名詞", topic:"pronombre", note:"女性を指す直接目的語は la に置き換える。" },
  { before:"¿Viste el partido? Sí, ", answer:"lo", after:" vi.", ja:"試合を見た？うん、見たよ。", label:"目的代名詞", topic:"pronombre", note:"男性単数の直接目的語（el partido）は lo に置き換える。" },
  { before:"¿Compraste los boletos? Sí, ", answer:"los", after:" compré.", ja:"チケットを買った？うん、買ったよ。", label:"目的代名詞", topic:"pronombre", note:"男性複数の直接目的語（los boletos）は los に置き換える。" },
  { before:"¿Necesitas la información? Sí, ", answer:"la", after:" necesito.", ja:"その情報が必要？うん、必要だよ。", label:"目的代名詞", topic:"pronombre", note:"女性単数の直接目的語（la información）は la に置き換える。" },
  { before:"Yo ", answer:"me visto", after:" rápido por las mañanas.", ja:"私は朝、素早く服を着る。", label:"vestirse（再帰動詞・現在形）", topic:"reflexivo", note:"vestirseは語根母音変化（e→i）動詞。yoの形はme visto。" },
  { before:"Ella ", answer:"se baña", after:" antes de dormir.", ja:"彼女は寝る前にお風呂に入る。", label:"bañarse（再帰動詞・現在形）", topic:"reflexivo", note:"三人称単数では再帰代名詞 se を使う。" },
  { before:"Nosotros ", answer:"nos sentamos", after:" en la primera fila.", ja:"私たちは最前列に座る。", label:"sentarse（再帰動詞・現在形）", topic:"reflexivo", note:"nosotrosでは再帰代名詞 nos を使う。" },
  { before:"¿Por qué ", answer:"te quedas", after:" tú en casa?", ja:"どうして君は家に残るの？", label:"quedarse（再帰動詞・現在形）", topic:"reflexivo", note:"túでは再帰代名詞 te を使う。" },
  { before:"Ellos ", answer:"se peinan", after:" frente al espejo.", ja:"彼らは鏡の前で髪をとかす。", label:"peinarse（再帰動詞・現在形）", topic:"reflexivo", note:"三人称複数では再帰代名詞 se を使う。" },
  { before:"Juan tiene más dinero ", answer:"que", after:" Pedro.", ja:"フアンはペドロより多くのお金を持っている。", label:"比較級", topic:"comparativo", note:"más+名詞+que で「〜より多くの…」を表す。" },
  { before:"Este ejercicio es menos difícil ", answer:"que", after:" el anterior.", ja:"この練習問題は前のものより簡単だ。", label:"比較級", topic:"comparativo", note:"menos+形容詞+que で「〜より少ない」を表す。" },
  { before:"Mi coche es tan rápido ", answer:"como", after:" el tuyo.", ja:"私の車は君のと同じくらい速い。", label:"同等比較", topic:"comparativo", note:"tan+形容詞+como で「〜と同じくらい」を表す。" },
  { before:"Ella es la ", answer:"más", after:" inteligente de la clase.", ja:"彼女はクラスで一番賢い。", label:"最上級", topic:"comparativo", note:"el/la+más+形容詞で「一番〜」を表す。" },
  { before:"Tengo tantos libros ", answer:"como", after:" tú.", ja:"私は君と同じくらいたくさんの本を持っている。", label:"同等比較", topic:"comparativo", note:"tanto/a/os/as+名詞+como で名詞の同等比較を表す。" },
  { before:"Esta película es peor ", answer:"que", after:" la anterior.", ja:"この映画は前のものより悪い。", label:"比較級", topic:"comparativo", note:"peor（もっと悪い、malの不規則比較級）の後もqueを使う。" },
  { before:"Nosotros ", answer:"somos", after:" estudiantes de español.", ja:"私たちはスペイン語の学生だ。", label:"ser / estar", topic:"ser_estar", note:"身分・所属を表すときは ser を使う。" },
  { before:"La puerta ", answer:"está", after:" abierta.", ja:"ドアが開いている。", label:"ser / estar", topic:"ser_estar", note:"動作の結果としての状態を表すときは estar+過去分詞を使う。" },
  { before:"Ellos ", answer:"están", after:" de vacaciones esta semana.", ja:"彼らは今週休暇中だ。", label:"ser / estar", topic:"ser_estar", note:"「esta semana（今週）」から一時的な状況だと分かるので estar を使う。" },
  { before:"Yo ", answer:"soy", after:" de Japón.", ja:"私は日本出身だ。", label:"ser / estar", topic:"ser_estar", note:"出身を表すときは ser de を使う。" },
  { before:"A mí ", answer:"me encanta", after:" viajar.", ja:"私は旅行が大好きだ。", label:"encantar（現在形）", topic:"gustar", note:"encantar（大好きだ）もgustar型の語順を取る。" },
  { before:"A nosotros ", answer:"nos falta", after:" tiempo.", ja:"私たちは時間が足りない。", label:"faltar（現在形）", topic:"gustar", note:"faltar（足りない）もgustar型。主語（tiempo）が単数なのでfalta。" },
  { before:"A ti ", answer:"te quedan", after:" diez pesos.", ja:"君にはあと10ペソ残っている。", label:"quedar（現在形）", topic:"gustar", note:"主語（diez pesos）が複数なので動詞も複数形quedanになる。" },
  { before:"A ella no ", answer:"le importa", after:" el precio.", ja:"彼女は値段を気にしない。", label:"importar（現在形）", topic:"gustar", note:"importar（気にする、重要だ）もgustar型の語順を取る。" },
  { before:"A ellos ", answer:"les fascinan", after:" los museos.", ja:"彼らは美術館に夢中だ。", label:"fascinar（現在形）", topic:"gustar", note:"主語（los museos）が複数なので動詞も複数形fascinanになる。" },
  { before:"¿Te doy la respuesta? Sí, ", answer:"te la", after:" doy.", ja:"答えを教えてあげようか？うん、それを教えてあげるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"te（間接）＋la（直接）は「te la」の順番のまま、seには変わらない。" },
  { before:"¿Le explicas la lección a tu hermano? Sí, ", answer:"se la", after:" explico.", ja:"弟にその授業を説明してあげる？うん、それを説明してあげるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"間接目的語leと直接目的語laが並ぶとき、leはseに変わる。" },
  { before:"¿Nos traes las bebidas? Sí, ", answer:"nos las", after:" traigo.", ja:"私たちに飲み物を持ってきてくれる？うん、それらを持ってくるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"nosはseに変わらず、そのままnos+las→nos lasの順で使う。" },
  { before:"¿Me prestas los apuntes? Sí, ", answer:"te los", after:" presto.", ja:"ノートを貸してくれる？うん、それを君に貸すよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"te（間接）＋los（直接）は「te los」の順番。" },
  { before:"¿Les mandas el paquete a ellos? Sí, ", answer:"se lo", after:" mando.", ja:"彼らに荷物を送ってあげる？うん、それを送ってあげるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"間接目的語lesと直接目的語loが並ぶとき、lesはseに変わる。" },
  { before:"Estoy pensando ", answer:"en", after:" el examen.", ja:"試験のことを考えている。", label:"前置詞（en/de）", topic:"preposicion", note:"pensar en（〜について考える）は決まった組み合わせ。" },
  { before:"Me alegro ", answer:"de", after:" tu éxito.", ja:"君の成功を嬉しく思う。", label:"前置詞（en/de）", topic:"preposicion", note:"alegrarse de（〜を喜ぶ）は決まった組み合わせ。" },
  { before:"Voy ", answer:"a", after:" pie al trabajo.", ja:"歩いて仕事に行く。", label:"前置詞（決まった言い回し）", topic:"preposicion", note:"ir a pie（歩いて行く）は決まった言い回し。" },
  { before:"El regalo es de parte ", answer:"de", after:" todos nosotros.", ja:"このプレゼントは私たち全員からです。", label:"前置詞（en/de）", topic:"preposicion", note:"de parte de（〜からの、〜を代表して）は決まった言い回し。" },
  { before:"Depende ", answer:"de", after:" el clima.", ja:"天気による。", label:"前置詞（en/de）", topic:"preposicion", note:"depender de（〜による）は決まった組み合わせ。" },
  { before:"Se preocupa mucho ", answer:"por", after:" su familia.", ja:"彼は家族のことをとても心配している。", label:"前置詞（決まった言い回し）", topic:"preposicion", note:"preocuparse por（〜を心配する）は決まった組み合わせ。" },
  { before:"Estoy harto ", answer:"de", after:" este ruido.", ja:"この騒音にはうんざりだ。", label:"前置詞（en/de）", topic:"preposicion", note:"harto de（〜にうんざりして）は決まった言い回し。" },
  { before:"Vamos ", answer:"de", after:" compras esta tarde.", ja:"今日の午後、買い物に行こう。", label:"前置詞（en/de）", topic:"preposicion", note:"ir de compras（買い物に行く）は決まった言い回し。" },
  { before:"¿Terminaste la tarea? Sí, ", answer:"la", after:" terminé.", ja:"宿題終わった？うん、終わったよ。", label:"目的代名詞", topic:"pronombre", note:"女性単数の直接目的語（la tarea）は la に置き換える。" },
  { before:"¿Perdiste las llaves? Sí, ", answer:"las", after:" perdí.", ja:"鍵をなくした？うん、なくしたよ。", label:"目的代名詞", topic:"pronombre", note:"女性複数の直接目的語（las llaves）は las に置き換える。" },
  { before:"¿Rompiste el plato? Sí, ", answer:"lo", after:" rompí.", ja:"お皿を割った？うん、割ったよ。", label:"目的代名詞", topic:"pronombre", note:"男性単数の直接目的語（el plato）は lo に置き換える。" },
  { before:"¿Invitaste a tus amigos? Sí, ", answer:"los", after:" invité.", ja:"友達を招待した？うん、招待したよ。", label:"目的代名詞", topic:"pronombre", note:"男性複数の直接目的語（a tus amigos）は los に置き換える。" },
  { before:"¿Llamaste a tu madre? Sí, ", answer:"la", after:" llamé.", ja:"お母さんに電話した？うん、電話したよ。", label:"目的代名詞", topic:"pronombre", note:"女性を指す直接目的語（a tu madre）は la に置き換える。" },
  { before:"¿Encontraste tu teléfono? Sí, ", answer:"lo", after:" encontré.", ja:"携帯電話見つかった？うん、見つかったよ。", label:"目的代名詞", topic:"pronombre", note:"男性単数の直接目的語（tu teléfono）は lo に置き換える。" },
  { before:"¿Leíste los mensajes? Sí, ", answer:"los", after:" leí.", ja:"メッセージ読んだ？うん、読んだよ。", label:"目的代名詞", topic:"pronombre", note:"男性複数の直接目的語（los mensajes）は los に置き換える。" },
  { before:"¿Escribiste la carta? Sí, ", answer:"la", after:" escribí.", ja:"手紙書いた？うん、書いたよ。", label:"目的代名詞", topic:"pronombre", note:"女性単数の直接目的語（la carta）は la に置き換える。" },
  { before:"Él ", answer:"se afeita", after:" todas las mañanas.", ja:"彼は毎朝ひげを剃る。", label:"afeitarse（再帰動詞・現在形）", topic:"reflexivo", note:"三人称単数では再帰代名詞 se を使う。" },
  { before:"Yo ", answer:"me maquillo", after:" antes de salir.", ja:"私は出かける前に化粧をする。", label:"maquillarse（再帰動詞・現在形）", topic:"reflexivo", note:"yoでは再帰代名詞 me を使う。" },
  { before:"El bebé ", answer:"se duerme", after:" rápido.", ja:"赤ちゃんはすぐに眠りにつく。", label:"dormirse（再帰動詞・現在形）", topic:"reflexivo", note:"dormirseはo→ueの語根母音変化動詞。三人称単数はse duerme。" },
  { before:"Nosotros ", answer:"nos vamos", after:" de vacaciones mañana.", ja:"私たちは明日休暇に出かける。", label:"irse（再帰動詞・現在形）", topic:"reflexivo", note:"irseは不規則動詞。nosotrosの形はnos vamos。" },
  { before:"¿Por qué ", answer:"te preocupas", after:" tú tanto?", ja:"どうして君はそんなに心配するの？", label:"preocuparse（再帰動詞・現在形）", topic:"reflexivo", note:"túでは再帰代名詞 te を使う。" },
  { before:"Ellos ", answer:"se enojan", after:" fácilmente.", ja:"彼らはすぐ怒る。", label:"enojarse（再帰動詞・現在形）", topic:"reflexivo", note:"三人称複数では再帰代名詞 se を使う。" },
  { before:"Este hotel es mejor ", answer:"que", after:" aquel.", ja:"このホテルはあのホテルより良い。", label:"比較級", topic:"comparativo", note:"mejor（もっと良い、buenoの不規則比較級）の後もqueを使う。" },
  { before:"Ana corre más rápido ", answer:"que", after:" Luis.", ja:"アナはルイスより速く走る。", label:"比較級", topic:"comparativo", note:"más+副詞+que で「〜より…」を表す。" },
  { before:"Tengo tanto trabajo ", answer:"como", after:" tú.", ja:"私は君と同じくらいたくさん仕事がある。", label:"同等比較", topic:"comparativo", note:"tanto+名詞+como で名詞の同等比較を表す。" },
  { before:"Este es el edificio más alto ", answer:"de", after:" la ciudad.", ja:"これは街で一番高い建物だ。", label:"最上級", topic:"comparativo", note:"最上級の範囲を示すときは「de+場所」を使う（enではない点に注意）。" },
  { before:"Su casa es tan grande ", answer:"como", after:" la mía.", ja:"彼の家は私の家と同じくらい大きい。", label:"同等比較", topic:"comparativo", note:"tan+形容詞+como で「〜と同じくらい」を表す。" },
  { before:"Hay menos gente aquí ", answer:"que", after:" ayer.", ja:"今日は昨日より人が少ない。", label:"比較級", topic:"comparativo", note:"menos+名詞+que で「〜より少ない」を表す。" },
  { before:"Este café ", answer:"está", after:" demasiado caliente.", ja:"このコーヒーは熱すぎる。", label:"ser / estar", topic:"ser_estar", note:"一時的な温度の状態を表すときは estar を使う。" },
  { before:"Mis padres ", answer:"son", after:" de México.", ja:"私の両親はメキシコ出身だ。", label:"ser / estar", topic:"ser_estar", note:"出身を表すときは ser de を使う。" },
  { before:"¿Cómo ", answer:"está", after:" tu abuela?", ja:"おばあさんの調子はどう？", label:"ser / estar", topic:"ser_estar", note:"体調・健康状態を尋ねるときは estar を使う。" },
  { before:"El concierto ", answer:"es", after:" en el estadio.", ja:"コンサートはスタジアムで行われる。", label:"ser / estar", topic:"ser_estar", note:"イベントが「どこで開催されるか」を表すときは ser を使う（estarではない特別なルール）。" },
  { before:"La ventana ", answer:"está", after:" rota.", ja:"窓が割れている。", label:"ser / estar", topic:"ser_estar", note:"動作の結果としての状態を表すときは estar+過去分詞を使う。" },
  { before:"Nosotros ", answer:"somos", after:" profesores.", ja:"私たちは教師だ。", label:"ser / estar", topic:"ser_estar", note:"職業を表すときは ser を使う。" },
  { before:"A mí ", answer:"me aburren", after:" las películas largas.", ja:"長い映画は退屈だ。", label:"aburrir（現在形）", topic:"gustar", note:"主語（las películas）が複数なので動詞も複数形aburrenになる。" },
  { before:"A ella ", answer:"le sorprende", after:" la noticia.", ja:"彼女はその知らせに驚いている。", label:"sorprender（現在形）", topic:"gustar", note:"sorprender（驚かせる）もgustar型の語順を取る。" },
  { before:"A nosotros ", answer:"nos preocupa", after:" el futuro.", ja:"私たちは将来が心配だ。", label:"preocupar（現在形）", topic:"gustar", note:"preocupar（心配させる）もgustar型の語順を取る。" },
  { before:"¿A ti ", answer:"te parece", after:" bien mi plan?", ja:"私の計画は君にとって良さそう？", label:"parecer（現在形）", topic:"gustar", note:"parecer（〜のように思える）もgustar型の語順を取る。" },
  { before:"A ellos ", answer:"les hace falta", after:" más tiempo.", ja:"彼らはもっと時間が必要だ。", label:"hacer falta（現在形）", topic:"gustar", note:"hacer falta（必要である）もgustar型の語順を取る。" },
  { before:"A mí ", answer:"me fastidia", after:" esperar.", ja:"待つのは私にとって煩わしい。", label:"fastidiar（現在形）", topic:"gustar", note:"fastidiar（うんざりさせる）もgustar型の語順を取る。" },
  { before:"¿Te presto mi bici? Sí, ", answer:"me la", after:" prestas.", ja:"自転車を貸してあげようか？うん、それを貸して。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"me（間接）＋la（直接）は「me la」の順番。" },
  { before:"¿Le compras el regalo a tu papá? Sí, ", answer:"se lo", after:" compro.", ja:"お父さんにプレゼントを買ってあげる？うん、それを買ってあげるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"leとloが並ぶとき、leはseに変わる。" },
  { before:"¿Nos enseñas la foto? Sí, ", answer:"nos la", after:" enseño.", ja:"私たちにその写真を見せてくれる？うん、見せるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"nosはseに変わらず、そのままnos+la→nos laの順で使う。" },
  { before:"¿Me das los boletos? Sí, ", answer:"te los", after:" doy.", ja:"チケットをくれる？うん、それを君にあげるよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"te（間接）＋los（直接）は「te los」の順番。" },
  { before:"¿Les cuentas el secreto a ellas? Sí, ", answer:"se lo", after:" cuento.", ja:"彼女たちに秘密を話す？うん、話すよ。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"lesとloが並ぶとき、lesはseに変わる。" },
  { before:"¿Te devuelvo las llaves? Sí, ", answer:"me las", after:" devuelves.", ja:"鍵を返してほしい？うん、それを私に返して。", label:"目的代名詞（二重）", topic:"pronombre_doble", note:"me（間接）＋las（直接）は「me las」の順番。" },
];

/* ---------- Listening / dictation items (2 blanks per sentence, ~100-140 chars) ---------- */
const LISTENING_ITEMS = [
  { segs:["Todos los días, mi madre se despierta muy ", " y prepara el ", " para toda la familia."],
    answers:["temprano","desayuno"], ja:"毎日、母はとても早く起きて、家族全員のために朝食を用意する。" },
  { segs:["El fin de semana pasado fuimos a la ", " y nadamos en el ", " toda la tarde."],
    answers:["playa","mar"], ja:"先週末、私たちはビーチに行って、午後じゅう海で泳いだ。" },
  { segs:["Cuando era ", ", vivía en un pueblo pequeño cerca de las ", "."],
    answers:["niño","montañas"], ja:"子供の頃、私は山の近くの小さな町に住んでいた。" },
  { segs:["Mi hermano trabaja en una ", " del centro y siempre llega ", " a casa."],
    answers:["oficina","tarde"], ja:"私の兄はダウンタウンのオフィスで働いていて、いつも遅く家に帰ってくる。" },
  { segs:["Ayer compré una ", " nueva porque la anterior ya estaba muy ", "."],
    answers:["camisa","vieja"], ja:"昨日、前のがもう古かったから新しいシャツを買った。" },
  { segs:["El próximo mes voy a ", " a México para visitar a mis ", "."],
    answers:["viajar","abuelos"], ja:"来月、祖父母を訪ねるためにメキシコへ旅行するつもりだ。" },
  { segs:["Necesito comprar ", " y ", " para hacer el pastel de cumpleaños."],
    answers:["leche","huevos"], ja:"誕生日ケーキを作るために牛乳と卵を買う必要がある。" },
  { segs:["Mi profesora dice que debo ", " más para hablar español con ", "."],
    answers:["practicar","fluidez"], ja:"先生は、流暢にスペイン語を話すためにもっと練習しなければならないと言う。" },
  { segs:["Después de la ", ", salió un hermoso ", " sobre la ciudad."],
    answers:["lluvia","arcoíris"], ja:"雨の後、街の上に美しい虹が出た。" },
  { segs:["El sábado por la noche, mis amigos y yo fuimos a ", " a una ", " muy divertida."],
    answers:["bailar","fiesta"], ja:"土曜の夜、友達と私はとても楽しいパーティーへ踊りに行った。" },
  { segs:["Mi abuelo siempre nos cuenta ", " interesantes sobre su ", "."],
    answers:["historias","juventud"], ja:"祖父はいつも若い頃についての面白い話をしてくれる。" },
  { segs:["Antes de dormir, me gusta leer un ", " o escuchar ", " tranquila."],
    answers:["libro","música"], ja:"寝る前に、本を読んだり静かな音楽を聴いたりするのが好きだ。" },
  { segs:["En la reunión de hoy, vamos a ", " el presupuesto y tomar una ", " importante."],
    answers:["revisar","decisión"], ja:"今日の会議では、予算を見直して重要な決断を下す予定だ。" },
  { segs:["Cada verano, mi familia y yo pasamos una ", " completa en la ", " de mis tíos."],
    answers:["semana","casa"], ja:"毎年夏、私と家族はおじ夫婦の家で丸一週間を過ごす。" },
  { segs:["El médico me recomendó dormir más y reducir el ", " para mejorar mi ", "."],
    answers:["estrés","salud"], ja:"医者は、健康を改善するためにもっと眠ってストレスを減らすよう勧めた。" },
];
