const VERBS = [
  { v:"hablar", ja:"話す",
    presente:["hablo","hablas","habla","hablamos","hablan"],
    indefinido:["hablé","hablaste","habló","hablamos","hablaron"],
    imperfecto:["hablaba","hablabas","hablaba","hablábamos","hablaban"],
    futuro:["hablaré","hablarás","hablará","hablaremos","hablarán"],
    condicional:["hablaría","hablarías","hablaría","hablaríamos","hablarían"],
    subjuntivo:["hable","hables","hable","hablemos","hablen"],
    perfecto:["he hablado","has hablado","ha hablado","hemos hablado","han hablado"],
    imperativo:["habla","hable","hablemos","hablen"] },
  { v:"comer", ja:"食べる",
    presente:["como","comes","come","comemos","comen"],
    indefinido:["comí","comiste","comió","comimos","comieron"],
    imperfecto:["comía","comías","comía","comíamos","comían"],
    futuro:["comeré","comerás","comerá","comeremos","comerán"],
    condicional:["comería","comerías","comería","comeríamos","comerían"],
    subjuntivo:["coma","comas","coma","comamos","coman"],
    perfecto:["he comido","has comido","ha comido","hemos comido","han comido"],
    imperativo:["come","coma","comamos","coman"] },
  { v:"vivir", ja:"住む/生きる",
    presente:["vivo","vives","vive","vivimos","viven"],
    indefinido:["viví","viviste","vivió","vivimos","vivieron"],
    imperfecto:["vivía","vivías","vivía","vivíamos","vivían"],
    futuro:["viviré","vivirás","vivirá","viviremos","vivirán"],
    condicional:["viviría","vivirías","viviría","viviríamos","vivirían"],
    subjuntivo:["viva","vivas","viva","vivamos","vivan"],
    perfecto:["he vivido","has vivido","ha vivido","hemos vivido","han vivido"],
    imperativo:["vive","viva","vivamos","vivan"] },
  { v:"ser", ja:"〜である",
    presente:["soy","eres","es","somos","son"],
    indefinido:["fui","fuiste","fue","fuimos","fueron"],
    imperfecto:["era","eras","era","éramos","eran"],
    futuro:["seré","serás","será","seremos","serán"],
    condicional:["sería","serías","sería","seríamos","serían"],
    subjuntivo:["sea","seas","sea","seamos","sean"],
    perfecto:["he sido","has sido","ha sido","hemos sido","han sido"],
    imperativo:["sé","sea","seamos","sean"] },
  { v:"estar", ja:"〜にいる",
    presente:["estoy","estás","está","estamos","están"],
    indefinido:["estuve","estuviste","estuvo","estuvimos","estuvieron"],
    imperfecto:["estaba","estabas","estaba","estábamos","estaban"],
    futuro:["estaré","estarás","estará","estaremos","estarán"],
    condicional:["estaría","estarías","estaría","estaríamos","estarían"],
    subjuntivo:["esté","estés","esté","estemos","estén"],
    perfecto:["he estado","has estado","ha estado","hemos estado","han estado"],
    imperativo:["está","esté","estemos","estén"] },
  { v:"tener", ja:"持つ",
    presente:["tengo","tienes","tiene","tenemos","tienen"],
    indefinido:["tuve","tuviste","tuvo","tuvimos","tuvieron"],
    imperfecto:["tenía","tenías","tenía","teníamos","tenían"],
    futuro:["tendré","tendrás","tendrá","tendremos","tendrán"],
    condicional:["tendría","tendrías","tendría","tendríamos","tendrían"],
    subjuntivo:["tenga","tengas","tenga","tengamos","tengan"],
    perfecto:["he tenido","has tenido","ha tenido","hemos tenido","han tenido"],
    imperativo:["ten","tenga","tengamos","tengan"] },
  { v:"ir", ja:"行く",
    presente:["voy","vas","va","vamos","van"],
    indefinido:["fui","fuiste","fue","fuimos","fueron"],
    imperfecto:["iba","ibas","iba","íbamos","iban"],
    futuro:["iré","irás","irá","iremos","irán"],
    condicional:["iría","irías","iría","iríamos","irían"],
    subjuntivo:["vaya","vayas","vaya","vayamos","vayan"],
    perfecto:["he ido","has ido","ha ido","hemos ido","han ido"],
    imperativo:["ve","vaya","vamos","vayan"] },
  { v:"hacer", ja:"する/作る",
    presente:["hago","haces","hace","hacemos","hacen"],
    indefinido:["hice","hiciste","hizo","hicimos","hicieron"],
    imperfecto:["hacía","hacías","hacía","hacíamos","hacían"],
    futuro:["haré","harás","hará","haremos","harán"],
    condicional:["haría","harías","haría","haríamos","harían"],
    subjuntivo:["haga","hagas","haga","hagamos","hagan"],
    perfecto:["he hecho","has hecho","ha hecho","hemos hecho","han hecho"],
    imperativo:["haz","haga","hagamos","hagan"] },
  { v:"poder", ja:"〜できる",
    presente:["puedo","puedes","puede","podemos","pueden"],
    indefinido:["pude","pudiste","pudo","pudimos","pudieron"],
    imperfecto:["podía","podías","podía","podíamos","podían"],
    futuro:["podré","podrás","podrá","podremos","podrán"],
    condicional:["podría","podrías","podría","podríamos","podrían"],
    subjuntivo:["pueda","puedas","pueda","podamos","puedan"],
    perfecto:["he podido","has podido","ha podido","hemos podido","han podido"],
    imperativo:["puede","pueda","podamos","puedan"] },
  { v:"querer", ja:"欲しい/したい",
    presente:["quiero","quieres","quiere","queremos","quieren"],
    indefinido:["quise","quisiste","quiso","quisimos","quisieron"],
    imperfecto:["quería","querías","quería","queríamos","querían"],
    futuro:["querré","querrás","querrá","querremos","querrán"],
    condicional:["querría","querrías","querría","querríamos","querrían"],
    subjuntivo:["quiera","quieras","quiera","queramos","quieran"],
    perfecto:["he querido","has querido","ha querido","hemos querido","han querido"],
    imperativo:["quiere","quiera","queramos","quieran"] },
];

const EXAMPLES = [
  { before:"Ayer yo ", verb:"hablar", tense:"indefinido", p:0, after:" con mi madre.", ja:"昨日、私は母と話した。" },
  { before:"Cuando era niño, yo ", verb:"ir", tense:"imperfecto", p:0, after:" a la escuela caminando.", ja:"子供の頃、私は歩いて学校に通っていた。" },
  { before:"Mañana nosotros ", verb:"comer", tense:"futuro", p:3, after:" en un restaurante nuevo.", ja:"明日、私たちは新しいレストランで食べるだろう。" },
  { before:"En tu lugar, yo ", verb:"hacer", tense:"condicional", p:0, after:" lo mismo.", ja:"あなたの立場なら、私も同じことをするだろう。" },
  { before:"¿", verb:"poder", tense:"condicional", p:1, after:" usted ayudarme?", ja:"手伝っていただけますか？（丁寧な依頼）" },
  { before:"Espero que tú ", verb:"tener", tense:"subjuntivo", p:1, after:" un buen viaje.", ja:"良い旅行になりますように。" },
  { before:"Quiero que ellos ", verb:"ser", tense:"subjuntivo", p:4, after:" felices.", ja:"彼らが幸せであってほしい。" },
  { before:"Yo nunca ", verb:"ir", tense:"perfecto", p:0, after:" a México.", ja:"私はメキシコに行ったことがない。" },
  { before:"¿Alguna vez tú ", verb:"comer", tense:"perfecto", p:1, after:" tacos de verdad?", ja:"本場のタコスを食べたことはありますか？" },
  { before:"¡", verb:"hablar", tense:"imperativo", p:0, after:" más despacio, por favor!", ja:"もっとゆっくり話してください！" },
  { before:"El año pasado, nosotros ", verb:"vivir", tense:"indefinido", p:3, after:" en España.", ja:"去年、私たちはスペインに住んだ。" },
  { before:"Normalmente, yo ", verb:"tener", tense:"presente", p:0, after:" mucho trabajo los lunes.", ja:"普段、月曜日は仕事がたくさんある。" },
  { before:"El próximo año, ellos ", verb:"estar", tense:"futuro", p:4, after:" en Japón.", ja:"来年、彼らは日本にいるだろう。" },
  { before:"Cuando éramos jóvenes, ", verb:"querer", tense:"imperfecto", p:3, after:" viajar mucho.", ja:"若い頃、私たちはたくさん旅行したいと思っていた。" },
  { before:"Este regalo es ", answer:"para", after:" ti.", ja:"このプレゼントは君のためのものだ。", label:"por / para", note:"para+人は「〜のために」という受益者・目的を表す。" },
  { before:"Caminamos ", answer:"por", after:" el parque.", ja:"私たちは公園を通って歩いた。", label:"por / para", note:"por は「〜を通って」という経路を表す。" },
  { before:"Trabajo ", answer:"para", after:" ganar dinero.", ja:"お金を稼ぐために働く。", label:"por / para", note:"para+動詞の原形は「〜するために」という目的を表す。" },
  { before:"Gracias ", answer:"por", after:" tu ayuda.", ja:"助けてくれてありがとう。", label:"por / para", note:"por は理由・原因（〜のおかげで、〜に対して）を表す。" },
  { before:"Necesito el informe ", answer:"para", after:" el lunes.", ja:"月曜日までにその報告書が必要だ。", label:"por / para", note:"para+期限は「〜までに」という締め切りを表す。" },
  { before:"Pasamos ", answer:"por", after:" tu casa ayer.", ja:"昨日君の家の前を通った。", label:"por / para", note:"por は「〜のそばを」という通過点を表す。" },
  { before:"Voy ", answer:"a", after:" la escuela todos los días.", ja:"毎日学校に行く。", label:"en / a", note:"行き先を表すときは a を使う（ir a + 場所）。" },
  { before:"Vivo ", answer:"en", after:" México.", ja:"メキシコに住んでいる。", label:"en / a", note:"「〜の中に」という所在を表すときは en を使う。" },
  { before:"¿Tienes el libro? Sí, ", answer:"lo", after:" tengo.", ja:"本を持ってる？うん、持ってるよ。", label:"目的代名詞", note:"男性単数の直接目的語（el libro）は lo に置き換える。" },
  { before:"¿Compraste las manzanas? Sí, ", answer:"las", after:" compré.", ja:"りんごを買った？うん、買ったよ。", label:"目的代名詞", note:"女性複数の直接目的語（las manzanas）は las に置き換える。" },
  { before:"", answer:"Le", after:" voy a dar un regalo a mi madre.", ja:"母にプレゼントをあげるつもりだ。", label:"目的代名詞", note:"間接目的語（〜に）は単数なら le、複数なら les で表す。" },
  { before:"", answer:"Les", after:" escribí una carta a mis amigos.", ja:"友人たちに手紙を書いた。", label:"目的代名詞", note:"間接目的語が複数のときは les を使う。" },
  { before:"¿Ves a Juan? Sí, ", answer:"lo", after:" veo.", ja:"フアンが見える？うん、見えるよ。", label:"目的代名詞", note:"男性の人を指す直接目的語も lo に置き換えられる。" },
  { before:"Yo ", answer:"me levanto", after:" a las siete de la mañana.", ja:"私は朝7時に起きる。", label:"levantarse（再帰動詞・現在形）", note:"再帰動詞は主語に合わせた再帰代名詞（me/te/se/nos/se）を動詞の前につける。" },
  { before:"Ella ", answer:"se llama", after:" María.", ja:"彼女はマリアという名前だ。", label:"llamarse（再帰動詞・現在形）", note:"llamarse は「〜という名前である」。三人称単数は se llama。" },
  { before:"Nosotros ", answer:"nos despertamos", after:" temprano los lunes.", ja:"私たちは月曜日早く目を覚ます。", label:"despertarse（再帰動詞・現在形）", note:"nosotros では再帰代名詞 nos を使う。" },
  { before:"¿A qué hora ", answer:"te acuestas", after:" tú?", ja:"何時に寝るの？", label:"acostarse（再帰動詞・現在形）", note:"tú では再帰代名詞 te を使う。" },
  { before:"Ellos ", answer:"se duchan", after:" por la mañana.", ja:"彼らは朝シャワーを浴びる。", label:"ducharse（再帰動詞・現在形）", note:"三人称複数では再帰代名詞 se を使う。" },
  { before:"Este coche es más caro ", answer:"que", after:" aquel.", ja:"この車はあの車より高い。", label:"比較級", note:"比較級は más+形容詞+que で「〜より…」を表す。" },
  { before:"Ella es ", answer:"tan", after:" alta como su hermana.", ja:"彼女は姉と同じくらい背が高い。", label:"同等比較", note:"同等比較は tan+形容詞+como で「〜と同じくらい」を表す。" },
  { before:"Tengo menos tiempo ", answer:"que", after:" tú.", ja:"私は君より時間が少ない。", label:"比較級", note:"menos+名詞+que で「〜より少ない」を表す。" },
  { before:"Mi hermano es el ", answer:"más", after:" alto de la familia.", ja:"私の兄は家族の中で一番背が高い。", label:"最上級", note:"最上級は el/la+más+形容詞で「一番〜」を表す。" },
  { before:"María ", answer:"es", after:" muy inteligente.", ja:"マリアはとても賢い。", label:"ser / estar", note:"性格・本質的な性質を表すときは ser を使う。" },
  { before:"Hoy yo ", answer:"estoy", after:" un poco cansado.", ja:"今日、私は少し疲れている。", label:"ser / estar", note:"一時的な状態を表すときは estar を使う。" },
  { before:"Madrid ", answer:"está", after:" en España.", ja:"マドリードはスペインにある。", label:"ser / estar", note:"場所・所在を表すときは estar を使う。" },
  { before:"¿Qué hora ", answer:"es", after:"?", ja:"何時ですか。", label:"ser / estar", note:"時刻を表すときは ser を使う。" },
  { before:"La sopa ", answer:"está", after:" fría.", ja:"スープが冷めている。", label:"ser / estar", note:"一時的な状態（温度など）は estar を使う。" },
  { before:"Él ", answer:"es", after:" médico.", ja:"彼は医者だ。", label:"ser / estar", note:"職業を表すときは ser を使う。" },
  { before:"A mí ", answer:"me gusta", after:" el chocolate.", ja:"私はチョコレートが好きだ。", label:"gustar（現在形）", topic:"gustar", note:"gustarは「主語＝好きな対象」。人は間接目的語代名詞（me/te/le/nos/les）で表す。" },
  { before:"A ella ", answer:"le duele", after:" la cabeza.", ja:"彼女は頭が痛い。", label:"doler（現在形）", topic:"gustar", note:"doler（痛い）もgustarと同じ語順パターンを取る。" },
  { before:"A nosotros ", answer:"nos interesa", after:" la historia.", ja:"私たちは歴史に興味がある。", label:"interesar（現在形）", topic:"gustar", note:"interesar（興味がある）もgustar型。主語は「歴史」なので単数形。" },
  { before:"A ellos ", answer:"les gustan", after:" los tacos.", ja:"彼らはタコスが好きだ。", label:"gustar（現在形）", topic:"gustar", note:"主語（los tacos）が複数なので、動詞も複数形gustanになる。" },
  { before:"A ti ", answer:"te molesta", after:" el ruido.", ja:"あなたは騒音が迷惑だ。", label:"molestar（現在形）", topic:"gustar", note:"molestar（迷惑だ）もgustar型の語順を取る。" },
  { before:"¿Le diste el regalo a Juan? Sí, ", answer:"se lo", after:" di.", ja:"フアンにプレゼントをあげた？うん、それを彼にあげたよ。", label:"目的代名詞（二重）", note:"間接目的語leと直接目的語loが並ぶとき、leはseに変わる。" },
  { before:"¿Me prestas tu coche? Sí, ", answer:"te lo", after:" presto.", ja:"車を貸してくれる？うん、それを君に貸すよ。", label:"目的代名詞（二重）", note:"間接目的語（te）＋直接目的語（lo）は「te lo」の順で並べる。" },
  { before:"¿Les enviaste la carta a ellos? Sí, ", answer:"se la", after:" envié.", ja:"彼らに手紙を送った？うん、それを彼らに送ったよ。", label:"目的代名詞（二重）", note:"間接目的語lesと直接目的語laが並ぶとき、lesはseに変わる。" },
  { before:"¿Nos vas a dar la noticia? Sí, ", answer:"se la", after:" voy a dar.", ja:"私たちにその知らせを教えてくれる？うん、それを教えるよ。", label:"目的代名詞（二重）", note:"間接目的語lesが対象のとき、laと組み合わさるとseになる。" },
  { before:"¿Me compras el libro? Sí, ", answer:"te lo", after:" compro.", ja:"その本を買ってくれる？うん、それを君に買うよ。", label:"目的代名詞（二重）", note:"間接目的語（te）＋直接目的語（lo）は必ずこの順番。" },
];
