const NEWS_ITEMS = [
  { date:"2026年6月11日", es:"México es una de las tres sedes de la Copa Mundial de la FIFA 2026, junto con Estados Unidos y Canadá. El torneo comenzó el 11 de junio en la Ciudad de México.",
    ja:"メキシコはアメリカ・カナダとともに2026年FIFAワールドカップの開催国の一つです。大会は6月11日にメキシコシティで開幕しました。",
    notes:[["sede","開催地"],["torneo","大会"],["comenzó","始まった（comenzarの点過去）"]] },
  { date:null, es:"La selección mexicana de fútbol ha tenido un buen momento reciente, con una defensa sólida que ha permitido pocos goles en sus últimos partidos.",
    ja:"メキシコ代表サッカーチームは最近好調で、直近の試合では失点の少ない堅実な守備が光っています。",
    notes:[["selección","代表チーム"],["defensa","守備"],["partidos","試合"]] },
  { date:null, es:"México es el país con más hablantes nativos de español en el mundo, por encima incluso de España.",
    ja:"メキシコは世界で最もネイティブのスペイン語話者数が多い国で、スペインをも上回っているとされています。",
    notes:[["hablantes nativos","ネイティブ話者"],["por encima de","〜を上回って"]] },
  { date:null, es:"El metro de la Ciudad de México es uno de los sistemas de transporte subterráneo más grandes de América Latina, con millones de pasajeros cada día.",
    ja:"メキシコシティの地下鉄はラテンアメリカでも最大級の地下交通網の一つで、毎日何百万人もの乗客が利用しています。",
    notes:[["transporte subterráneo","地下交通"],["pasajeros","乗客"]] },
  { date:null, es:"La Universidad Nacional Autónoma de México (UNAM) es una de las universidades más grandes de América Latina, y su campus principal está declarado Patrimonio de la Humanidad por la UNESCO.",
    ja:"メキシコ国立自治大学(UNAM)はラテンアメリカ最大級の大学の一つで、そのメインキャンパスはユネスコ世界遺産にも登録されています。",
    notes:[["universidad","大学"],["Patrimonio de la Humanidad","世界遺産"]] },
  { date:null, es:"México es reconocido por su gran biodiversidad y se encuentra entre los países con mayor número de especies de plantas y animales del mundo.",
    ja:"メキシコは非常に生物多様性が豊かなことで知られ、世界でも植物・動物の種数が多い国の一つとされています。",
    notes:[["biodiversidad","生物多様性"],["especies","種"]] },
  { date:"2010年", es:"La gastronomía mexicana fue declarada Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2010, gracias a su riqueza de ingredientes y tradiciones regionales.",
    ja:"メキシコ料理は2010年にユネスコの無形文化遺産に登録されました。豊かな食材と各地域の伝統が評価されています。",
    notes:[["gastronomía","食文化・料理"],["ingredientes","食材"],["tradiciones","伝統"]] },
  { date:null, es:"El peso mexicano es una de las monedas más antiguas de América, con una historia que se remonta a la época colonial.",
    ja:"メキシコペソはアメリカ大陸で最も歴史の古い通貨の一つで、その起源は植民地時代にさかのぼります。",
    notes:[["moneda","通貨"],["se remonta a","〜にさかのぼる"]] },
  { date:null, es:"Cada año, millones de turistas visitan sitios arqueológicos como Chichén Itzá y Teotihuacán, testimonios de las civilizaciones maya y mesoamericana.",
    ja:"毎年、何百万人もの観光客がチチェン・イッツァやテオティワカンといった遺跡を訪れます。これらはマヤ文明や中米文明の証です。",
    notes:[["sitios arqueológicos","遺跡"],["testimonios","証・証言"],["civilizaciones","文明"]] },
  { date:null, es:"El cine mexicano ha ganado varios premios Óscar en la última década, con directores como Alejandro González Iñárritu, Alfonso Cuarón y Guillermo del Toro entre los más reconocidos internacionalmente.",
    ja:"メキシコ映画はこの10年余りで複数のアカデミー賞を獲得しており、アレハンドロ・ゴンサレス・イニャリトゥ、アルフォンソ・キュアロン、ギレルモ・デル・トロといった監督が国際的に高く評価されています。",
    notes:[["cine","映画"],["premios","賞"],["reconocidos","評価されている"]] },
  { date:null, es:"La música regional mexicana, incluyendo géneros como el corrido y la banda, ha ganado gran popularidad internacional en plataformas de streaming en los últimos años.",
    ja:"コリードやバンダといったジャンルを含むメキシコのリージョナル音楽は、近年ストリーミングサービスを通じて世界的な人気を集めています。",
    notes:[["música regional","地方音楽・リージョナル音楽"],["plataformas de streaming","ストリーミングサービス"]] },
  { date:"2026年7月26日", es:"El 26 de julio de 2026 comenzó una nueva temporada de 'La Casa de los Famosos México', uno de los realities más comentados del país, con quince habitantes entre actores, cantantes e influencers conviviendo bajo cámaras las 24 horas.",
    ja:"2026年7月26日、メキシコで最も話題になるリアリティー番組の一つ「ラ・カサ・デ・ロス・ファモソス・メヒコ」の新シーズンが始まりました。俳優・歌手・インフルエンサーを含む15人が、24時間カメラの前で共同生活をします。",
    notes:[["habitantes","（番組内の）住人・出演者"],["conviviendo","共同生活をしている"],["las 24 horas","24時間ずっと"]] },
  { date:"2026年7月", es:"Entre los habitantes de este reality, la conductora y modelo Yanet García destaca como una de las más seguidas en redes sociales, con varios millones de seguidores en sus cuentas.",
    ja:"この番組の出演者の中で、司会者・モデルのヤネット・ガルシアはSNSで最もフォロワーが多い一人として注目されており、数百万人のフォロワーを抱えています。",
    notes:[["conductora","司会者"],["seguidores","フォロワー"],["destacar","際立つ、目立つ"]] },
  { date:null, es:"El género de los corridos tumbados, con artistas como Peso Pluma, Fuerza Regida y Natanael Cano, ha seguido rompiendo récords de streaming y superando incluso a géneros pop en algunos rankings globales.",
    ja:"コリードス・トゥンバードスというジャンルは、ペソ・プルマやフエルサ・レヒーダ、ナタナエル・カノといったアーティストによって、世界的なランキングでポップスすら上回るほどストリーミング記録を更新し続けています。",
    notes:[["romper récords","記録を更新する"],["superar","上回る"],["rankings globales","世界ランキング"]] },
  { date:null, es:"El cantante mexicano Peso Pluma colaboró con el rapero estadounidense Kanye West en la canción 'Last Breath', mezclando corridos tumbados con hip-hop en un tema que llamó la atención internacional.",
    ja:"メキシコの歌手ペソ・プルマは、アメリカのラッパー、カニエ・ウェストと楽曲「Last Breath」でコラボレーションし、コリードス・トゥンバードスとヒップホップを融合させて国際的な注目を集めました。",
    notes:[["colaborar","コラボする"],["mezclar","混ぜ合わせる"],["llamar la atención","注目を集める"]] },
  { date:"2026年7月17日", es:"El 17 de julio de 2026 ocurrió un fuerte sismo de magnitud 7.4 con epicentro cerca de Ciudad Hidalgo, en el estado de Chiapas. Desde entonces, el Servicio Sismológico Nacional ha registrado más de mil réplicas en la zona.",
    ja:"2026年7月17日、チアパス州シウダー・イダルゴ付近を震源とするマグニチュード7.4の強い地震が発生しました。それ以来、国立地震観測局はこの地域で1000回を超える余震を観測しています。",
    notes:[["sismo","地震"],["epicentro","震源地"],["réplica","余震"]] },
  { date:"2026年7月19日", es:"La Copa Mundial de la FIFA 2026, organizada conjuntamente por México, Estados Unidos y Canadá, concluyó el 19 de julio con la final disputada en un estadio de Nueva York, tras 39 días y 104 partidos.",
    ja:"メキシコ・アメリカ・カナダの3カ国共催で行われたFIFAワールドカップ2026は、39日間・104試合を経て、7月19日にニューヨークのスタジアムで決勝が行われ幕を閉じました。",
    notes:[["organizado conjuntamente","共同開催された"],["disputada","争われた（試合が）"],["concluir","終わる、幕を閉じる"]] },
  { date:"2026年7月15日", es:"El ciclo escolar 2025-2026 terminó el 15 de julio en México, marcando el inicio de las vacaciones de verano para millones de estudiantes en todo el país.",
    ja:"メキシコでは2025〜2026年度が7月15日に終了し、全国の何百万人もの生徒たちにとって夏休みの始まりとなりました。",
    notes:[["ciclo escolar","学年度"],["marcar el inicio de","〜の始まりとなる"]] },
  { date:"2026年7月28日", es:"Se registraron varios sismos en Chiapas la mañana del 28 de julio, con el más fuerte de magnitud 4.7, como parte de la actividad de réplicas tras el sismo de magnitud 7.4 ocurrido el 17 de julio.",
    ja:"7月28日の朝、チアパス州で複数の地震が観測され、最も強いものはマグニチュード4.7でした。7月17日に発生したマグニチュード7.4の地震の余震活動の一環です。",
    notes:[["sismo","地震"],["réplica","余震"],["magnitud","マグニチュード"]] },
  { date:"2026年7月31日", es:"La Secretaría de Salud reiteró su meta de eliminar la hepatitis C antes de 2030, impulsando la estrategia de Servicio Universal de Salud que permite recibir atención médica sin importar la afiliación institucional.",
    ja:"保健省は2030年までにC型肝炎を撲滅するという目標を改めて表明し、所属機関に関わらず医療を受けられる「ユニバーサル・ヘルス・サービス」戦略を推進しています。",
    notes:[["meta","目標"],["eliminar","撲滅する、なくす"],["afiliación","所属、加入"]] },
  { date:"2026年7月31日", es:"La Pensión para el Bienestar de las Personas Adultas Mayores subió a 6,400 pesos bimestrales en 2026, con el objetivo de llegar a 14 millones de personas de 65 años y más en todo el país.",
    ja:"高齢者向け福祉年金は2026年に隔月6,400ペソに引き上げられ、全国の65歳以上の1,400万人に行き渡ることを目標としています。",
    notes:[["pensión","年金"],["bimestral","隔月の"],["objetivo","目標"]] },
  { date:"2026年7月31日", es:"La delegación mexicana se mantiene en el primer lugar del medallero de los Juegos Centroamericanos y del Caribe Santo Domingo 2026, con más de 181 medallas, destacando en ciclismo BMX, clavados, natación, remo y tiro con arco.",
    ja:"メキシコ代表団は、サントドミンゴ2026中米カリブ海競技大会のメダル獲得数で181個以上を獲得し首位を維持しています。BMX、飛び込み、水泳、ボート、アーチェリーで活躍しています。",
    notes:[["delegación","代表団"],["medallero","メダル獲得数表"],["destacar en","〜で活躍する"]] },
];
