const NEWS_ITEMS = [
  { es:"El 17 de julio de 2026, un fuerte terremoto de magnitud 7.3 sacudió la costa del Pacífico frente a Chiapas, en el sur de México. Se emitió una alerta de tsunami de manera temporal, pero hasta ahora no se han reportado daños graves ni víctimas.",
    ja:"2026年7月17日、メキシコ南部チアパス州沖の太平洋岸でマグニチュード7.3の強い地震が発生しました。一時津波警報が出されましたが、今のところ大きな被害や犠牲者の報告はありません。",
    notes:[["terremoto","地震"],["alerta de tsunami","津波警報"],["daños","被害"],["víctimas","犠牲者"]] },
  { es:"México es una de las tres sedes de la Copa Mundial de la FIFA 2026, junto con Estados Unidos y Canadá. El torneo comenzó el 11 de junio en la Ciudad de México.",
    ja:"メキシコはアメリカ・カナダとともに2026年FIFAワールドカップの開催国の一つです。大会は6月11日にメキシコシティで開幕しました。",
    notes:[["sede","開催地"],["torneo","大会"],["comenzó","始まった（comenzarの点過去）"]] },
  { es:"La selección mexicana de fútbol ha tenido un buen momento reciente, con una defensa sólida que ha permitido pocos goles en sus últimos partidos.",
    ja:"メキシコ代表サッカーチームは最近好調で、直近の試合では失点の少ない堅実な守備が光っています。",
    notes:[["selección","代表チーム"],["defensa","守備"],["partidos","試合"]] },
  { es:"México es el país con más hablantes nativos de español en el mundo, por encima incluso de España.",
    ja:"メキシコは世界で最もネイティブのスペイン語話者数が多い国で、スペインをも上回っているとされています。",
    notes:[["hablantes nativos","ネイティブ話者"],["por encima de","〜を上回って"]] },
  { es:"El metro de la Ciudad de México es uno de los sistemas de transporte subterráneo más grandes de América Latina, con millones de pasajeros cada día.",
    ja:"メキシコシティの地下鉄はラテンアメリカでも最大級の地下交通網の一つで、毎日何百万人もの乗客が利用しています。",
    notes:[["transporte subterráneo","地下交通"],["pasajeros","乗客"]] },
  { es:"La Universidad Nacional Autónoma de México (UNAM) es una de las universidades más grandes de América Latina, y su campus principal está declarado Patrimonio de la Humanidad por la UNESCO.",
    ja:"メキシコ国立自治大学(UNAM)はラテンアメリカ最大級の大学の一つで、そのメインキャンパスはユネスコ世界遺産にも登録されています。",
    notes:[["universidad","大学"],["Patrimonio de la Humanidad","世界遺産"]] },
  { es:"México es reconocido por su gran biodiversidad y se encuentra entre los países con mayor número de especies de plantas y animales del mundo.",
    ja:"メキシコは非常に生物多様性が豊かなことで知られ、世界でも植物・動物の種数が多い国の一つとされています。",
    notes:[["biodiversidad","生物多様性"],["especies","種"]] },
  { es:"La gastronomía mexicana fue declarada Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2010, gracias a su riqueza de ingredientes y tradiciones regionales.",
    ja:"メキシコ料理は2010年にユネスコの無形文化遺産に登録されました。豊かな食材と各地域の伝統が評価されています。",
    notes:[["gastronomía","食文化・料理"],["ingredientes","食材"],["tradiciones","伝統"]] },
  { es:"El peso mexicano es una de las monedas más antiguas de América, con una historia que se remonta a la época colonial.",
    ja:"メキシコペソはアメリカ大陸で最も歴史の古い通貨の一つで、その起源は植民地時代にさかのぼります。",
    notes:[["moneda","通貨"],["se remonta a","〜にさかのぼる"]] },
  { es:"Cada año, millones de turistas visitan sitios arqueológicos como Chichén Itzá y Teotihuacán, testimonios de las civilizaciones maya y mesoamericana.",
    ja:"毎年、何百万人もの観光客がチチェン・イッツァやテオティワカンといった遺跡を訪れます。これらはマヤ文明や中米文明の証です。",
    notes:[["sitios arqueológicos","遺跡"],["testimonios","証・証言"],["civilizaciones","文明"]] },
  { es:"El cine mexicano ha ganado varios premios Óscar en la última década, con directores como Alejandro González Iñárritu, Alfonso Cuarón y Guillermo del Toro entre los más reconocidos internacionalmente.",
    ja:"メキシコ映画はこの10年余りで複数のアカデミー賞を獲得しており、アレハンドロ・ゴンサレス・イニャリトゥ、アルフォンソ・キュアロン、ギレルモ・デル・トロといった監督が国際的に高く評価されています。",
    notes:[["cine","映画"],["premios","賞"],["reconocidos","評価されている"]] },
  { es:"La música regional mexicana, incluyendo géneros como el corrido y la banda, ha ganado gran popularidad internacional en plataformas de streaming en los últimos años.",
    ja:"コリードやバンダといったジャンルを含むメキシコのリージョナル音楽は、近年ストリーミングサービスを通じて世界的な人気を集めています。",
    notes:[["música regional","地方音楽・リージョナル音楽"],["plataformas de streaming","ストリーミングサービス"]] },
];
