/* ----------------------------------------------------------------------
   SCENARIOS — シチュエーション別によく使うフレーズ集
   実際の生活の中でよく聞かれる・よく使う場面ごとにまとめています。
   少しずつ増やしていく前提のファイルです。
------------------------------------------------------------------------- */
const SCENARIOS = [
  { icon:"☕", title:"カフェで", items:[
    { es:"¿Qué va a tomar?", ja:"何になさいますか？", note:"店員が注文を聞くときの決まり文句" },
    { es:"Un café americano, por favor.", ja:"アメリカーノを一つください。", note:"" },
    { es:"¿Con leche entera, deslactosada o de almendra?", ja:"牛乳は普通のにしますか、乳糖不使用にしますか、アーモンドミルクにしますか？", note:"ミルクの種類を聞かれる定番の質問" },
    { es:"Con leche entera está bien.", ja:"普通の牛乳で大丈夫です。", note:"" },
    { es:"¿Para tomar aquí o para llevar?", ja:"店内でお召し上がりですか、お持ち帰りですか？", note:"" },
    { es:"Para llevar, por favor.", ja:"持ち帰りでお願いします。", note:"" },
    { es:"¿De qué tamaño lo quiere?", ja:"サイズはどうしますか？", note:"" },
    { es:"El chico/mediano/grande, por favor.", ja:"小/中/大でお願いします。", note:"" },
    { es:"¿Le pongo azúcar?", ja:"お砂糖入れますか？", note:"" },
    { es:"Sin azúcar, gracias.", ja:"砂糖なしでお願いします。", note:"" },
  ]},
  { icon:"🍽️", title:"レストランで", items:[
    { es:"Una mesa para dos, por favor.", ja:"2名でお願いします。", note:"入店時の定番フレーズ" },
    { es:"¿Ya sabe qué va a ordenar?", ja:"ご注文はお決まりですか？", note:"" },
    { es:"¿Me puede traer la carta/el menú?", ja:"メニューをいただけますか？", note:"" },
    { es:"¿Qué me recomienda?", ja:"何かおすすめはありますか？", note:"" },
    { es:"Para mí, este.", ja:"私はこれにします。", note:"メニューを指しながら注文するときに便利" },
    { es:"¿Está picante este platillo?", ja:"この料理は辛いですか？", note:"" },
    { es:"Sin cilantro, por favor.", ja:"パクチー抜きでお願いします。", note:"苦手な食材を伝えるときの例" },
    { es:"La cuenta, por favor.", ja:"お会計お願いします。", note:"" },
    { es:"¿La cuenta junta o por separado?", ja:"お会計は一緒にしますか、別々にしますか？", note:"割り勘したいときによく聞かれる" },
    { es:"Por separado, por favor.", ja:"別々でお願いします。", note:"" },
    { es:"¿Aceptan tarjeta?", ja:"カードは使えますか？", note:"" },
    { es:"Estuvo muy rico, gracias.", ja:"とても美味しかったです、ありがとうございます。", note:"会計時のちょっとした一言" },
  ]},
  { icon:"🛒", title:"スーパー・買い物で", items:[
    { es:"¿Dónde están las verduras?", ja:"野菜はどこにありますか？", note:"" },
    { es:"¿Tiene esto en otro color/talla?", ja:"これの他の色/サイズはありますか？", note:"" },
    { es:"¿Me lo puedo probar?", ja:"試着してもいいですか？", note:"" },
    { es:"¿Necesita bolsa?", ja:"袋は必要ですか？", note:"メキシコではエコバッグ持参が一般的、聞かれることが多い" },
    { es:"No, gracias, traigo mi propia bolsa.", ja:"いいえ、大丈夫です、自分の袋を持ってきました。", note:"" },
    { es:"¿Cuánto cuesta esto?", ja:"これはいくらですか？", note:"" },
    { es:"¿Tiene algo más barato?", ja:"もっと安いものはありますか？", note:"" },
    { es:"¿Puedo pagar con tarjeta?", ja:"カードで払えますか？", note:"" },
    { es:"¿Me da un recibo, por favor?", ja:"レシートをいただけますか？", note:"" },
  ]},
  { icon:"🏨", title:"ホテルで", items:[
    { es:"Tengo una reservación a nombre de...", ja:"〜の名前で予約しています。", note:"チェックイン時の定番フレーズ" },
    { es:"¿A qué hora es el check-in/check-out?", ja:"チェックイン/チェックアウトは何時ですか？", note:"" },
    { es:"¿El desayuno está incluido?", ja:"朝食は含まれていますか？", note:"" },
    { es:"¿Tienen wifi? ¿Cuál es la contraseña?", ja:"Wi-Fiはありますか？パスワードは何ですか？", note:"" },
    { es:"¿Me pueden dar otra almohada/toalla?", ja:"枕/タオルをもう一枚もらえますか？", note:"" },
    { es:"El aire acondicionado no funciona.", ja:"エアコンが動きません。", note:"トラブル報告の定番表現" },
    { es:"¿Pueden guardar mi equipaje después del check-out?", ja:"チェックアウト後に荷物を預かってもらえますか？", note:"" },
    { es:"¿Me pueden llamar un taxi?", ja:"タクシーを呼んでもらえますか？", note:"" },
  ]},
  { icon:"🚕", title:"タクシー・配車で", items:[
    { es:"¿A cuánto me sale a...?", ja:"〜まではいくらくらいですか？", note:"" },
    { es:"Lléveme a esta dirección, por favor.", ja:"この住所まで連れて行ってください。", note:"住所を見せながら言うと確実" },
    { es:"¿Cuánto tiempo se hace hasta ahí?", ja:"そこまでどれくらい時間がかかりますか？", note:"" },
    { es:"¿Puede parar aquí, por favor?", ja:"ここで止めてもらえますか？", note:"" },
    { es:"¿Me puede esperar unos minutos?", ja:"数分待ってもらえますか？", note:"" },
    { es:"¿Cuánto es?", ja:"おいくらですか？", note:"" },
    { es:"Quédese con el cambio.", ja:"おつりは取っておいてください。", note:"チップ代わりによく使う表現" },
  ]},
  { icon:"🛫", title:"空港で", items:[
    { es:"¿Dónde está el mostrador de la aerolínea...?", ja:"〜航空のカウンターはどこですか？", note:"" },
    { es:"Quiero facturar mi equipaje.", ja:"荷物を預けたいです。", note:"" },
    { es:"¿Cuál es mi puerta de embarque?", ja:"搭乗ゲートはどこですか？", note:"" },
    { es:"¿A qué hora empieza el abordaje?", ja:"搭乗は何時から始まりますか？", note:"" },
    { es:"Mi vuelo se retrasó.", ja:"私のフライトが遅延しました。", note:"" },
    { es:"¿Dónde recojo mi equipaje?", ja:"荷物はどこで受け取りますか？", note:"" },
    { es:"Vengo de vacaciones.", ja:"観光で来ました。", note:"入国審査でよく聞かれる質問への回答例" },
    { es:"Me quedo una semana.", ja:"1週間滞在します。", note:"入国審査でよく聞かれる" },
  ]},
  { icon:"💊", title:"薬局・病院で", items:[
    { es:"¿Tiene algo para el dolor de cabeza?", ja:"頭痛に効くものはありますか？", note:"" },
    { es:"Me duele la garganta.", ja:"喉が痛いです。", note:"" },
    { es:"¿Necesito receta para esto?", ja:"これには処方箋が必要ですか？", note:"" },
    { es:"¿Cómo debo tomar esto?", ja:"これはどう飲めばいいですか？", note:"" },
    { es:"Soy alérgico/a a...", ja:"私は〜アレルギーです。", note:"アレルギー申告は重要な一言" },
    { es:"Necesito ver a un médico.", ja:"医者に診てもらう必要があります。", note:"" },
    { es:"¿Dónde está la sala de emergencias?", ja:"救急外来はどこですか？", note:"" },
    { es:"No me siento bien.", ja:"体調が良くないです。", note:"" },
  ]},
  { icon:"🧭", title:"道を尋ねる・尋ねられる", items:[
    { es:"¿Cómo llego a...?", ja:"〜へはどう行けばいいですか？", note:"" },
    { es:"¿Está lejos de aquí?", ja:"ここから遠いですか？", note:"" },
    { es:"Está a dos cuadras de aquí.", ja:"ここから2ブロック先です。", note:"道を教えるときの定番表現" },
    { es:"Siga derecho y luego dé vuelta a la izquierda.", ja:"まっすぐ行って、それから左に曲がってください。", note:"" },
    { es:"¿Se puede ir caminando?", ja:"歩いて行けますか？", note:"" },
    { es:"Perdón, ¿me puede ayudar? Estoy perdido/a.", ja:"すみません、助けてもらえますか？道に迷ってしまって。", note:"" },
    { es:"¿Qué autobús/línea debo tomar?", ja:"どのバス/路線に乗ればいいですか？", note:"" },
  ]},
];
