/* ----------------------------------------------------------------------
   SCENARIOS — シチュエーション別によく使うフレーズ集
   実際の生活の中でよく聞かれる・よく使う場面ごとにまとめています。
   少しずつ増やしていく前提のファイルです。
------------------------------------------------------------------------- */
const SCENARIOS = [
  { icon:"☕", title:"カフェで", items:[
    { es:"¿Qué va a tomar?", ja:"何になさいますか？", note:"店員が注文を聞くときの決まり文句" },
    { es:"Un café americano, por favor.", ja:"アメリカーノを一つください。", note:"" },
    { es:"¿Con leche entera, deslactosada o de almendra?", ja:"牛乳は普通のにしますか、乳糖不使用にしますか、アーモンドミルクにしますか？", note:"ミルクの種類を聞かれる定番の質問" },
    { es:"Con leche entera está bien.", ja:"普通の牛乳で大丈夫です。", note:"" },
    { es:"¿Para tomar aquí o para llevar?", ja:"店内でお召し上がりですか、お持ち帰りですか？", note:"" },
    { es:"Para llevar, por favor.", ja:"持ち帰りでお願いします。", note:"" },
    { es:"¿De qué tamaño lo quiere?", ja:"サイズはどうしますか？", note:"" },
    { es:"El chico/mediano/grande, por favor.", ja:"小/中/大でお願いします。", note:"" },
    { es:"¿Le pongo azúcar?", ja:"お砂糖入れますか？", note:"" },
    { es:"Sin azúcar, gracias.", ja:"砂糖なしでお願いします。", note:"" },
  ]},
  { icon:"🍽️", title:"レストランで", items:[
    { es:"Una mesa para dos, por favor.", ja:"2名でお願いします。", note:"入店時の定番フレーズ" },
    { es:"¿Ya sabe qué va a ordenar?", ja:"ご注文はお決まりですか？", note:"" },
    { es:"¿Me puede traer la carta/el menú?", ja:"メニューをいただけますか？", note:"" },
    { es:"¿Qué me recomienda?", ja:"何かおすすめはありますか？", note:"" },
    { es:"Para mí, este.", ja:"私はこれにします。", note:"メニューを指しながら注文するときに便利" },
    { es:"¿Está picante este platillo?", ja:"この料理は辛いですか？", note:"" },
    { es:"Sin cilantro, por favor.", ja:"パクチー抜きでお願いします。", note:"苦手な食材を伝えるときの例" },
    { es:"La cuenta, por favor.", ja:"お会計お願いします。", note:"" },
    { es:"¿La cuenta junta o por separado?", ja:"お会計は一緒にしますか、別々にしますか？", note:"割り勘したいときによく聞かれる" },
    { es:"Por separado, por favor.", ja:"別々でお願いします。", note:"" },
    { es:"¿Aceptan tarjeta?", ja:"カードは使えますか？", note:"" },
    { es:"Soy alérgico/a a los cacahuates.", ja:"私はピーナッツアレルギーです。", note:"食材名を入れ替えて使える定番フレーズ（mariscos＝甲殻類、gluten＝グルテンなど）" },
    { es:"¿Este platillo tiene nueces o lácteos?", ja:"この料理にナッツや乳製品は入っていますか？", note:"" },
    { es:"¿Tienen opciones vegetarianas/veganas?", ja:"ベジタリアン/ヴィーガン向けのメニューはありますか？", note:"" },
    { es:"¿La propina está incluida?", ja:"チップは含まれていますか？", note:"メキシコでは通常含まれていない。人数が多いと自動でservicioが加算される店もある" },
    { es:"¿El servicio ya está incluido en la cuenta?", ja:"サービス料はもう会計に含まれていますか？", note:"propina（チップ、任意）とservicio/cargo por servicio（サービス料、団体客などで自動加算されることがある）は別物。servicioが入っていれば追加のpropinaは必須ではないが、気持ちで少し足す人も多い" },
    { es:"¿Cuánto se deja de propina normalmente?", ja:"普通どれくらいチップを渡すものですか？", note:"目安は10〜15%程度（地域・店による）" },
    { es:"Le voy a dejar la propina en efectivo.", ja:"チップは現金で置いていきます。", note:"" },
    { es:"Estuvo muy rico, gracias.", ja:"とても美味しかったです、ありがとうございます。", note:"会計時のちょっとした一言" },
  ]},
  { icon:"🛒", title:"スーパー・買い物で", items:[
    { es:"¿Dónde están las verduras?", ja:"野菜はどこにありますか？", note:"" },
    { es:"¿Tiene esto en otro color/talla?", ja:"これの他の色/サイズはありますか？", note:"" },
    { es:"¿Me lo puedo probar?", ja:"試着してもいいですか？", note:"" },
    { es:"¿Necesita bolsa?", ja:"袋は必要ですか？", note:"メキシコではエコバッグ持参が一般的、聞かれることが多い" },
    { es:"No, gracias, traigo mi propia bolsa.", ja:"いいえ、大丈夫です、自分の袋を持ってきました。", note:"" },
    { es:"¿Cuánto cuesta esto?", ja:"これはいくらですか？", note:"" },
    { es:"¿Tiene algo más barato?", ja:"もっと安いものはありますか？", note:"" },
    { es:"¿Puedo pagar con tarjeta?", ja:"カードで払えますか？", note:"" },
    { es:"¿Me da un recibo, por favor?", ja:"レシートをいただけますか？", note:"" },
  ]},
  { icon:"🏨", title:"ホテルで", items:[
    { es:"Tengo una reservación a nombre de...", ja:"〜の名前で予約しています。", note:"チェックイン時の定番フレーズ" },
    { es:"¿A qué hora es el check-in/check-out?", ja:"チェックイン/チェックアウトは何時ですか？", note:"" },
    { es:"¿El desayuno está incluido?", ja:"朝食は含まれていますか？", note:"" },
    { es:"¿Tienen wifi? ¿Cuál es la contraseña?", ja:"Wi-Fiはありますか？パスワードは何ですか？", note:"" },
    { es:"¿Me pueden dar otra almohada/toalla?", ja:"枕/タオルをもう一枚もらえますか？", note:"" },
    { es:"El aire acondicionado no funciona.", ja:"エアコンが動きません。", note:"トラブル報告の定番表現" },
    { es:"¿Pueden guardar mi equipaje después del check-out?", ja:"チェックアウト後に荷物を預かってもらえますか？", note:"" },
    { es:"¿Me pueden llamar un taxi?", ja:"タクシーを呼んでもらえますか？", note:"" },
  ]},
  { icon:"🚕", title:"タクシー・配車で", items:[
    { es:"¿A cuánto me sale a...?", ja:"〜まではいくらくらいですか？", note:"" },
    { es:"Lléveme a esta dirección, por favor.", ja:"この住所まで連れて行ってください。", note:"住所を見せながら言うと確実" },
    { es:"¿Cuánto tiempo se hace hasta ahí?", ja:"そこまでどれくらい時間がかかりますか？", note:"" },
    { es:"¿Puede parar aquí, por favor?", ja:"ここで止めてもらえますか？", note:"" },
    { es:"¿Me puede esperar unos minutos?", ja:"数分待ってもらえますか？", note:"" },
    { es:"¿Cuánto es?", ja:"おいくらですか？", note:"" },
    { es:"Quédese con el cambio.", ja:"おつりは取っておいてください。", note:"チップ代わりによく使う表現" },
  ]},
  { icon:"🛫", title:"空港で", items:[
    { es:"¿Dónde está el mostrador de la aerolínea...?", ja:"〜航空のカウンターはどこですか？", note:"" },
    { es:"Quiero facturar mi equipaje.", ja:"荷物を預けたいです。", note:"" },
    { es:"¿Cuál es mi puerta de embarque?", ja:"搭乗ゲートはどこですか？", note:"" },
    { es:"¿A qué hora empieza el abordaje?", ja:"搭乗は何時から始まりますか？", note:"" },
    { es:"Mi vuelo se retrasó.", ja:"私のフライトが遅延しました。", note:"" },
    { es:"¿Dónde recojo mi equipaje?", ja:"荷物はどこで受け取りますか？", note:"" },
    { es:"Vengo de vacaciones.", ja:"観光で来ました。", note:"入国審査でよく聞かれる質問への回答例" },
    { es:"Me quedo una semana.", ja:"1週間滞在します。", note:"入国審査でよく聞かれる" },
  ]},
  { icon:"💊", title:"薬局・病院で", items:[
    { es:"¿Tiene algo para el dolor de cabeza?", ja:"頭痛に効くものはありますか？", note:"" },
    { es:"Me duele la garganta.", ja:"喉が痛いです。", note:"" },
    { es:"¿Necesito receta para esto?", ja:"これには処方箋が必要ですか？", note:"" },
    { es:"¿Cómo debo tomar esto?", ja:"これはどう飲めばいいですか？", note:"" },
    { es:"Soy alérgico/a a...", ja:"私は〜アレルギーです。", note:"アレルギー申告は重要な一言" },
    { es:"Necesito ver a un médico.", ja:"医者に診てもらう必要があります。", note:"" },
    { es:"¿Dónde está la sala de emergencias?", ja:"救急外来はどこですか？", note:"" },
    { es:"No me siento bien.", ja:"体調が良くないです。", note:"" },
  ]},
  { icon:"🧭", title:"道を尋ねる・尋ねられる", items:[
    { es:"¿Cómo llego a...?", ja:"〜へはどう行けばいいですか？", note:"" },
    { es:"¿Está lejos de aquí?", ja:"ここから遠いですか？", note:"" },
    { es:"Está a dos cuadras de aquí.", ja:"ここから2ブロック先です。", note:"道を教えるときの定番表現" },
    { es:"Siga derecho y luego dé vuelta a la izquierda.", ja:"まっすぐ行って、それから左に曲がってください。", note:"" },
    { es:"¿Se puede ir caminando?", ja:"歩いて行けますか？", note:"" },
    { es:"Perdón, ¿me puede ayudar? Estoy perdido/a.", ja:"すみません、助けてもらえますか？道に迷ってしまって。", note:"" },
    { es:"¿Qué autobús/línea debo tomar?", ja:"どのバス/路線に乗ればいいですか？", note:"" },
  ]},
  { icon:"🗣️", title:"よく使う命令形フレーズ", items:[
    { es:"Ven / Venga.", ja:"来て（túに対して）／来てください（ustedに対して）。", note:"venirの命令形。túとustedの2つの形を併記" },
    { es:"Espera / Espere un momento.", ja:"ちょっと待って／お待ちください。", note:"esperarの命令形" },
    { es:"Mira / Mire esto.", ja:"これ見て／これをご覧ください。", note:"mirarの命令形。相手の注意を引くときによく使う" },
    { es:"Escucha / Escuche.", ja:"聞いて／お聞きください。", note:"escucharの命令形" },
    { es:"¡Cuidado!", ja:"気をつけて！", note:"動詞ではなく名詞そのものを使う定番の警告表現" },
    { es:"Ayúdame, por favor.", ja:"手伝って、お願い。", note:"ayudar+me（代名詞）の命令形" },
    { es:"Siéntate / Siéntese, por favor.", ja:"座って／お座りください。", note:"sentarseの再帰命令形" },
    { es:"Cállate.", ja:"黙って。", note:"callarseの再帰命令形。かなり直接的な言い方なので使う相手に注意" },
    { es:"Apúrate / Apúrese, por favor.", ja:"急いで／お急ぎください。", note:"apurarseの再帰命令形" },
    { es:"Dame eso, por favor.", ja:"それをちょうだい。", note:"dar+me（代名詞）の命令形" },
    { es:"Ten cuidado.", ja:"気をつけてね。", note:"tenerの命令形、cuidadoとセットでよく使う" },
    { es:"Quédate / Quédese aquí.", ja:"ここにいて／ここにいてください。", note:"quedarseの再帰命令形" },
    { es:"Sígueme / Sígame, por favor.", ja:"ついてきて／ついてきてください。", note:"seguir+me（代名詞）の命令形" },
    { es:"No te preocupes / No se preocupe.", ja:"心配しないで／ご心配なさらず。", note:"preocuparseの否定命令形" },
    { es:"No te vayas.", ja:"行かないで。", note:"irseの否定命令形" },
    { es:"Pásame la sal, por favor.", ja:"塩取って。", note:"pasar+me（代名詞）の命令形、食卓での定番" },
    { es:"Repite, por favor.", ja:"もう一度言って。", note:"repetirの命令形" },
    { es:"Vamos.", ja:"行こう。", note:"irのnosotros命令形（勧誘）、日常でとてもよく使う" },
  ]},
  { icon:"📱", title:"電話・SNSでのやり取り", items:[
    { es:"¿Bueno?", ja:"もしもし？", note:"メキシコでの電話の出方の定番（他地域ではdiga/alóなど）" },
    { es:"¿Con quién hablo?", ja:"どちら様ですか？", note:"" },
    { es:"¿Está Juan, por favor?", ja:"フアンさんいらっしゃいますか？", note:"" },
    { es:"Un momento, por favor, ahora le paso.", ja:"少々お待ちください、今おつなぎします。", note:"" },
    { es:"Se cortó la llamada.", ja:"電話が切れちゃった。", note:"" },
    { es:"Te mando un mensaje después.", ja:"あとでメッセージ送るね。", note:"" },
    { es:"¿Me puedes llamar cuando puedas?", ja:"手が空いたら電話してもらえる？", note:"" },
    { es:"No tengo señal aquí.", ja:"ここ電波が入らないんだ。", note:"" },
    { es:"Se me acabó la batería.", ja:"バッテリーが切れちゃった。", note:"" },
  ]},
  { icon:"💬", title:"雑談・スモールトーク", items:[
    { es:"¿A qué te dedicas?", ja:"お仕事は何をされていますか？", note:"初対面でよく聞かれる質問" },
    { es:"¿De dónde eres?", ja:"出身はどこですか？", note:"" },
    { es:"¿Cuánto tiempo llevas viviendo aquí?", ja:"ここに住んでどれくらいですか？", note:"" },
    { es:"¡Qué calor/frío hace hoy!", ja:"今日は暑いね/寒いね！", note:"天気の話は定番の雑談" },
    { es:"¿Tienes planes para el fin de semana?", ja:"週末の予定ある？", note:"" },
    { es:"¡Cuánto tiempo sin verte!", ja:"久しぶりだね！", note:"" },
    { es:"Nos vemos pronto, ¿va?", ja:"また近いうちに会おうね？", note:"" },
    { es:"Que te vaya bien.", ja:"うまくいきますように。", note:"別れ際によく使う一言" },
  ]},
  { icon:"🏠", title:"部屋探し・賃貸で", items:[
    { es:"Estoy buscando un departamento en renta.", ja:"賃貸のアパートを探しています。", note:"" },
    { es:"¿Cuánto es la renta mensual?", ja:"月々の家賃はいくらですか？", note:"" },
    { es:"¿Los servicios están incluidos?", ja:"光熱費は含まれていますか？", note:"" },
    { es:"¿Se necesita depósito?", ja:"敷金は必要ですか？", note:"" },
    { es:"¿Se permiten mascotas?", ja:"ペットは飼えますか？", note:"" },
    { es:"¿Cuándo puedo mudarme?", ja:"いつ引っ越せますか？", note:"" },
    { es:"¿Cuánto tiempo dura el contrato?", ja:"契約期間はどれくらいですか？", note:"" },
    { es:"El departamento está amueblado.", ja:"その部屋は家具付きです。", note:"" },
  ]},
  { icon:"🚨", title:"緊急時のフレーズ", items:[
    { es:"¡Ayuda!", ja:"助けて！", note:"緊急時に一番大事な一言" },
    { es:"Llame a la policía, por favor.", ja:"警察を呼んでください。", note:"" },
    { es:"Necesito un médico urgentemente.", ja:"至急医者が必要です。", note:"" },
    { es:"Me robaron mi cartera.", ja:"財布を盗まれました。", note:"" },
    { es:"Perdí mi pasaporte.", ja:"パスポートをなくしました。", note:"" },
    { es:"¿Dónde está la embajada japonesa?", ja:"日本大使館はどこですか？", note:"" },
    { es:"No me siento bien, necesito ayuda.", ja:"体調が悪いです、助けが必要です。", note:"" },
    { es:"Hubo un accidente.", ja:"事故がありました。", note:"" },
  ]},
  { icon:"💭", title:"相槌・フィラー（会話をつなぐ言葉）", items:[
    { es:"Ajá.", ja:"うんうん。", note:"相手の話を聞いている合図の相槌、最も基本的なもの" },
    { es:"Claro.", ja:"もちろん、その通り。", note:"同意の相槌" },
    { es:"Sí, sí.", ja:"うんうん、そうそう。", note:"強い同意・相槌" },
    { es:"Ya veo.", ja:"なるほど。", note:"" },
    { es:"¿En serio?", ja:"本当に？マジで？", note:"驚きの相槌" },
    { es:"No puede ser.", ja:"うそでしょ、そんな。", note:"驚きの相槌" },
    { es:"Este... / Esto...", ja:"えーと…", note:"言葉に詰まったときのフィラー" },
    { es:"O sea...", ja:"つまり…、要するに…", note:"言い換えるときのフィラー" },
    { es:"Bueno...", ja:"ええと…、まあ…", note:"話し始めや、話題を変えるときのフィラー" },
    { es:"Pues...", ja:"うーん…、まあ…", note:"考えながら話すときのフィラー、非常によく使われる" },
    { es:"A ver...", ja:"えーと…（考える）", note:"考えをまとめるときのフィラー" },
    { es:"Digo...", ja:"というか…（言い直し）", note:"言い直すときに使う" },
    { es:"¿Me explico?", ja:"伝わってる？分かる？", note:"説明の後に確認する一言" },
    { es:"¿Sabes?", ja:"でしょ？分かるでしょ？", note:"文末につけて共感を求める相槌" },
    { es:"Fíjate que...", ja:"実はさ…、聞いて…", note:"話を切り出すときの前置き" },
    { es:"No sé, ¿tú qué crees?", ja:"どうかな、君はどう思う？", note:"相手に意見を振るときの一言" },
  ]},
];
